- name: gather distribution facts
  setup:
    gather_subset: distribution,!min
  failed_when: ansible_facts.distribution is not defined
  when: ansible_facts.distribution is not defined

- name: gather service_mgr and pkg_mgr
  setup:
    gather_subset: pkg_mgr,service_mgr,!min
  failed_when:
  - ansible_facts.pkg_mgr is not defined or
    ansible_facts.service_mgr is not defined
  when:
  - ansible_facts.pkg_mgr is not defined or
    ansible_facts.service_mgr is not defined

- name: gather chroot fact
  setup:
    gather_subset: chroot,!min
  failed_when: ansible_facts.is_chroot is not defined
  when: ansible_facts.is_chroot is not defined

- name: detect whether system is running
  shell: IFS= read -r -d '' cmd </proc/1/cmdline ; printf "%s\n" "$cmd"
  check_mode: no
  register: ld_init_check
  changed_when: no

- import_tasks: "{{ ld_prep_cond_file }}"
  vars:
    ld_prep_file: lib/package-openssh-server.yml
    ld_rule_names:
    - sshd_use_approved_macs
    - sshd_use_approved_ciphers
